# Generated by Django 3.2.9 on 2021-11-11 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealership_name', models.CharField(max_length=50)),
                ('dealership_x_coordinate', models.DecimalField(decimal_places=7, max_digits=12)),
                ('dealership_y_coordinate', models.DecimalField(decimal_places=7, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=50)),
                ('car_brand', models.CharField(max_length=50)),
                ('car_production_year', models.DateField(max_length=50)),
                ('car_type', models.CharField(max_length=50)),
                ('car_price', models.CharField(max_length=50)),
                ('car_state', models.CharField(choices=[('New', 'New'), ['Used', 'Used']], max_length=50)),
                ('DealershipFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardealership.dealership')),
            ],
        ),
    ]
