# Generated by Django 3.2.9 on 2021-11-11 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cardealership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_color',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
