# Generated by Django 3.2.9 on 2021-11-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealership', '0002_car_car_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_color',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
