# Generated by Django 3.2.9 on 2021-11-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealership', '0003_alter_car_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_id',
            field=models.IntegerField(default=-1),
        ),
    ]
