# Generated by Django 3.2.9 on 2021-11-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealership', '0004_car_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_production_year',
            field=models.CharField(max_length=10),
        ),
    ]
