# Generated by Django 3.2.9 on 2021-11-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealership', '0005_alter_car_car_production_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_color',
            field=models.CharField(default='', max_length=50),
        ),
    ]
