# Generated by Django 3.2.9 on 2021-11-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealership', '0006_alter_car_car_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='DealershipFK',
            field=models.IntegerField(default=1),
        ),
    ]
