# Generated by Django 3.2.9 on 2021-12-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealership', '0007_alter_car_dealershipfk'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_image',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
